shinyUI(
pageWithSidebar(
headerPanel("Outcome of Care Measures by State"),
sidebarPanel(
radioButtons("id1", "Outcome",
c("Heart Attack" = "heart attack",
"Heart Failure" = "heart failure",
"Pneumonia" = "pneumonia")),
radioButtons("id2","Function",
c("Best"="1",
"Rank All"="2",
"Top 10"="3")),
selectInput("State", "State",
            c("Alabama" = "AL",
              "Alaska" = "AK",
              "Arizona" = "AZ",
		  "Arkansas" = "AR",
		  "California" = "CA",
		  "Colorado" = "CO",
		  "Conneticut" = "CT",
		  "Delaware" = "DE",
		  "Florida" = "FL",
		  "Georgia" = "GA",
		  "Hawaii" = "HI",
		  "Idaho" = "ID",
		  "Illinois" = "IL",
		  "Indiana" = "IN",
		  "Iowa" = "IA",
		  "Kansas" = "KS",
		  "Kentucky" = "KY",
		  "Louisiana" = "LA",
		  "Maine" = "ME",
		  "Maryland"="MD",
		  "Massachusetts"="MA",
		  "Michigan"="MI",
		  "Minnesota"="MN",
		  "Mississippi" = "MS",
		  "Missouri" = "MO",
		  "Montana" = "MT",
		  "Nebraska" = "NE",
		  "Nevada" = "NV",
		  "New Hampshire" = "NH",
		  "New Jersey" = "NJ",
		  "New Mexico" ="NM",
		  "New York" = "NY",
		  "North Carolina" = "NC",
		  "North Dakota" = "ND",
		  "Ohio" = "OH",
		  "Oklahoma" ="OK",
		  "Oregon" = "OR",
		  "Pennsylvania" = "PA",
		  "Rhode Island" = "RI",
		  "South Caroline" = "SC",
		  "South Dakota" = "SD",
		  "Tennesse" = "TN",
		  "Texas" = "TX",
		  "Utah" = "UT",
		  "Vermont" = "VT",
		  "Virginia" = "VA",
		  "Washington" = "WA",
		  "West Virginia" = "WV",
		  "Wisconsin" = "WI",
		  "Wyoming" = "WY"
)),
actionButton("do","Submit")
),
mainPanel(
tabsetPanel(
      tabPanel("Results", textOutput("text1")), 
      tabPanel("About", includeText("About.txt")) 
    )
)
))